import Coffe from "./assets/coffe.jpg";



export const Products = [
  {
    id: 0,
    code: "P1020492577",
    name: "Café el alba",
    description: "el que te deja la pija calva ",
    category: 1,
    price: 25000,
    stock: 80,
    image: Coffe,
  },
  {
    id: 1,
    code: "P1020492577",
    name: "Café el alba",
    description: "el que te deja la pija calva ",
    category: 1,
    price: 25000,
    stock: 80,
    image: Coffe,
  },
  {
    id: 2,
    code: "P1020492577",
    name: "Café el alba",
    description: "el que te deja la pija calva ",
    category: 1,
    price: 25000,
    stock: 80,
    image: Coffe,
  },
  {
    id: 3,
    code: "P1020492577",
    name: "Café el alba",
    description: "el que te deja la pija calva ",
    category: 1,
    price: 25000,
    stock: 80,
    image: Coffe,
  },
  {
    id: 4,
    code: "P1020492577",
    name: "Café el alba",
    description: "el que te deja la pija calva ",
    category: 1,
    price: 25000,
    stock: 80,
    image: Coffe,
  },
  {
    id: 5,
    code: "P1020492577",
    name: "Café el alba",
    description: "el que te deja la pija calva ",
    category: 1,
    price: 25000,
    stock: 80,
    image: Coffe,
  },
  {
    id: 6,
    code: "P1020492577",
    name: "Café el alba",
    description: "el que te deja la pija calva ",
    category: 1,
    price: 25000,
    stock: 80,
    image: Coffe,
  },
  {
    id: 7,
    code: "P1020492577",
    name: "Café el alba",
    description: "el que te deja la pija calva ",
    category: 1,
    price: 25000,
    stock: 80,
    image: Coffe,
  },
  {
    id: 8,
    code: "P1020492577",
    name: "Café el alba",
    description: "el que te deja la pija calva ",
    category: 1,
    price: 25000,
    stock: 80,
    image: Coffe,
  },
  {
    id: 9,
    code: "P1020492577",
    name: "Café el alba",
    description: "el que te deja la pija calva ",
    category: 1,
    price: 25000,
    stock: 80,
    image: Coffe,
  },
];
